export enum Genre {
    ACTION, ADVENTURE, ANIMATION, BIOGRAPHY, COMEDY, CRIME, DOCUMENTARY, DRAMA, FAMILY, FANTASY, HISTORY, HORROR,
    MUSIC, MUSICAL, MYSTERY, ROMANCE, SCIFI, SHORT,SPORT, THRILLER, WAR, WESTERN, OTHER
}
